// All user-facing text externalized for future i18n readiness

export const strings = {
  app: {
    name: 'OSPOS',
    tagline: 'A cash register on your phone.',
    version: '1.0.0',
    license: 'Open Source — MIT License',
  },
  onboarding: {
    modeSelectTitle: 'How do you want to get paid?',
    cashOnlyTitle: 'Cash Only',
    cashOnlyDescription: 'No account needed. No internet required. Start selling in under a minute.',
    cashOnlyBadge: 'Free',
    acceptCardsTitle: 'Accept Cards',
    acceptCardsDescription: 'Process card payments with a 1% fee. Requires account setup.',
    acceptCardsBadge: '1% per transaction',
    back: 'Back',
    skip: 'Skip',
    businessNameTitle: "What's your business called?",
    businessNameSubtitle: 'This appears on receipts',
    businessNamePlaceholder: 'My Business',
    currencyTitle: 'What currency do you use?',
    currencySubtitle: 'Sets the currency symbol for prices',
    taxRateTitle: "What's your sales tax rate?",
    taxRateSubtitle: "Enter 0 if you don't charge sales tax",
    taxRateNoTax: 'No Tax',
    receiptFooterTitle: 'Add a receipt message',
    receiptFooterSubtitle: 'A short note at the bottom of every receipt',
    receiptFooterPlaceholder: 'Thank you for your purchase!',
    finalTitle: "You're all set!",
    finalBusinessName: 'Business',
    finalCurrency: 'Currency',
    finalTaxRate: 'Tax Rate',
    finalAddMenu: 'Add Menu Items',
    finalStartSelling: 'Start Selling',
    continue: 'Continue',
  },
  stripeAuth: {
    registerTitle: 'Create Your Account',
    loginTitle: 'Welcome Back',
    subtitle: 'Required to process card payments',
    emailPlaceholder: 'Email address',
    passwordPlaceholder: 'Password (8+ characters)',
    registerButton: 'Create Account',
    loginButton: 'Sign In',
    switchToLogin: 'Already have an account? Sign In',
    switchToRegister: "Don't have an account? Create One",
    registerFailed: 'Registration Failed',
    loginFailed: 'Login Failed',
  },
  menuBuilder: {
    title: 'Your Menu',
    addItem: '+ Add Item',
    startSelling: 'Start Selling',
    emptyState: 'Add your first item to get started.',
    itemName: 'Item Name',
    itemPrice: 'Price',
    itemCategory: 'Category (optional)',
    itemPhoto: 'Add Photo',
    editItem: 'Edit Item',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    nameRequired: 'Name is required',
    priceRequired: 'Price is required',
    invalidPrice: 'Enter a valid price',
  },
  order: {
    title: 'Order',
    empty: 'Tap items to build an order',
    clear: 'Clear',
    charge: 'Charge',
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'Total',
    processing: 'Processing...',
    success: 'Payment successful',
    editMenu: 'Edit Menu',
  },
  payment: {
    title: 'Payment',
    cash: 'Cash',
    card: 'Tap to Pay on iPhone',
    cardComingSoon: 'Set up your account to accept card and contactless payments.',
    tipTitle: 'Add a tip?',
    noTip: 'No Tip',
    customTip: 'Custom',
    cashTendered: 'Cash Tendered',
    change: 'Change',
    exactCash: 'Exact Cash',
    confirm: 'Confirm Payment',
    skip: 'Skip',
    creatingPayment: 'Creating payment...',
    lookingForReader: 'Looking for reader...',
    connectingTapToPay: 'Connecting Tap to Pay on iPhone...',
    connectingReader: 'Connecting reader...',
    presentCard: 'Present card...',
    confirming: 'Confirming...',
    paymentFailed: 'Payment Failed',
    offlineUnavailable: 'Offline — unavailable',
    noReaderAvailable: 'Tap to Pay on iPhone is not enabled. Set it up or pair a Bluetooth reader in Settings.',
  },
  receipt: {
    title: 'Payment Complete',
    newOrder: 'New Order',
    total: 'Total',
    method: 'Payment Method',
    time: 'Time',
    subtotal: 'Subtotal',
    tax: 'Tax',
    tip: 'Tip',
    printReceipt: 'Print Receipt',
    printed: 'Printed',
    printSentToPrinter: 'Receipt sent to printer',
    printFailed: 'Print Failed',
    printFailedMessage: 'Could not print receipt',
    textReceipt: 'Text Receipt',
    emailReceipt: 'Email Receipt',
    phoneNumber: 'Phone number',
    emailAddress: 'Email address',
    sent: 'Sent',
    failed: 'Failed',
    send: 'Send',
    cancel: 'Cancel',
  },
  summary: {
    title: 'Summary',
    today: "Today's Sales",
    totalSales: 'Total Sales',
    transactions: 'Transactions',
    cashTotal: 'Cash',
    cardTotal: 'Card',
    average: 'Average',
    history: 'Transaction History',
    noTransactions: 'No transactions today',
    share: 'Share',
    exportCsv: 'Export CSV',
    exportSuccess: 'CSV exported successfully',
  },
  settings: {
    title: 'Settings',
    businessName: 'Business Name',
    businessNamePlaceholder: 'Your Business',
    taxRate: 'Tax Rate (%)',
    taxRatePlaceholder: '0',
    currency: 'Currency',
    autoBackup: 'Auto-Backup (Weekly)',
    backupNow: 'Back Up Now',
    backupSuccess: 'Backup saved',
    receiptFooter: 'Receipt Footer',
    receiptFooterPlaceholder: 'Thank you for your purchase!',
    upgradeToPaid: 'Upgrade to Card Payments',
    upgradeHint: 'Accept cards with a 1% per-transaction fee',
    helpSupport: 'Help & Support',
    about: 'About',
    taxNote: 'Tax is calculated as a simple percentage. Consult your accountant for jurisdiction-specific requirements.',
    testMode: 'Test Mode',
    testModeActive: 'Test mode active — no real charges will be processed',
    exitTestMode: 'Exit Test Mode',
    exitTestModeConfirm: 'Exit Test Mode and process real payments?',
    sync: 'Sync',
    synced: 'Synced',
    tapToRetry: 'Tap to force retry',
    account: 'Account',
    openStripeDashboard: 'Open Stripe Dashboard',
    receiptPrinter: 'Receipt Printer',
    printerConnected: 'Printer connected',
    disconnect: 'Disconnect',
    scanForPrinters: 'Scan for Printers',
    scanning: 'Scanning...',
    noPrintersFound: 'No Printers Found',
    noPrintersFoundMessage: 'Make sure your Bluetooth printer is turned on and nearby.',
    connected: 'Connected',
    connectFailed: 'Failed',
    connectFailedMessage: 'Could not connect to printer',
    retryTriggered: 'Retry triggered',
    github: 'GitHub',
  },
  transactionDetail: {
    title: 'Transaction Details',
    date: 'Date',
    payment: 'Payment',
    cash: 'Cash',
    card: 'Card',
    items: 'Items',
    confirmRefund: 'Confirm Refund',
    refundConfirmMessage: 'Refund to card?',
    error: 'Error',
    invalidRefundAmount: 'Enter a valid refund amount',
    refundProcessed: 'Refund Processed',
    refundedMessage: 'has been refunded.',
    refundFailed: 'Refund Failed',
    refundFailedMessage: 'Please try again.',
    fullRefund: 'Full Refund',
    partialRefund: 'Partial Refund',
    amount: 'Amount',
    processRefund: 'Process Refund',
    issueRefund: 'Issue Refund',
  },
  disputes: {
    title: 'Disputes',
    disputeDetail: 'Dispute Detail',
    reason: 'Reason:',
    notSpecified: 'Not specified',
    status: 'Status:',
    deadline: 'Deadline:',
    submitEvidence: 'Submit Evidence',
    explainCharge: 'Explain the charge...',
    takePhoto: 'Take Photo of Evidence',
    photoSelected: 'Photo selected',
    provideEvidence: 'Please provide evidence text or an image',
    success: 'Success',
    evidenceSubmitted: 'Evidence submitted successfully',
    submitFailed: 'Could not submit evidence. Try again.',
    noActiveDisputes: 'No active disputes',
    noDeadline: 'No deadline',
    deadlinePassed: 'Deadline passed',
    dueToday: 'Due today',
    dueTomorrow: 'Due tomorrow',
    daysLeft: 'days left',
  },
  ttpoi: {
    sectionTitle: 'Tap to Pay on iPhone',
    ready: 'Tap to Pay on iPhone is ready',
    notSetUp: 'Not Set Up',
    unavailable: 'Unavailable',
    setUp: 'Set Up',
    viewGuide: 'View Guide',
    incompatible: 'This device doesn\'t support Tap to Pay on iPhone. Requires iPhone XS or later with iOS 16.0+.',
    osUpdateRequired: 'iOS Update Required',
    osUpdateMessage: 'Tap to Pay on iPhone requires iOS 16.0 or later. Please update your device in Settings > General > Software Update.',
    // Awareness modal — Apple-approved copy (Value Proposition)
    awarenessTitle: 'Tap to Pay on iPhone',
    awarenessSubtitle: 'Accept physical debit and credit cards as well as Apple Pay and other digital wallets.\n\nRight on your iPhone.',
    awarenessEnable: 'Enable Now',
    awarenessNotNow: 'Not Now',
    // Setup screen — Apple-approved copy
    setupTitle: 'Tap to Pay on iPhone',
    setupDescription: 'With Tap to Pay on iPhone and OSPOS, you can accept all types of in-person, contactless payments right on your iPhone\u2014no extra hardware needed.',
    setupRequirements: 'Device Requirements',
    setupRequirementDevice: 'iPhone XS or later',
    setupRequirementOS: 'iOS 16.0 or later',
    setupRequirementPasscode: 'Passcode enabled',
    setupAcceptTerms: 'Accept Terms & Conditions',
    setupAcceptTermsNote: 'You\'ll be asked to review and accept Apple\'s Terms & Conditions for Tap to Pay on iPhone.',
    configuring: 'Setting up Tap to Pay on iPhone...',
    configured: 'Tap to Pay on iPhone is ready!',
    configDone: 'Done',
    // Education screens — Apple-approved "How to use" copy
    educationTitle: 'Accepting payments is easy.',
    educationCard: 'Contactless Cards',
    educationCardDesc: 'Your customer holds their card horizontally at the top of your iPhone, over the contactless symbol for a few seconds. When you see the Done checkmark, the transaction is being processed.',
    educationWallet: 'Apple Pay & Digital Wallets',
    educationWalletDesc: 'Your customer holds their device at the top of your iPhone, over the contactless symbol for a few seconds. When you see the Done checkmark, the transaction is being processed.',
    educationTips: 'Privacy and security built in.',
    educationTipsDesc: 'Tap to Pay on iPhone uses the built-in security and privacy features of iPhone to help protect your business and customer data. Apple doesn\'t store card numbers on Apple servers.',
    // iOS 18+ branch: shown behind Apple's ProximityReaderDiscovery overlay
    educationReadyTitle: 'You\'re ready to accept payments.',
    educationReadyDesc: 'You\'ve just seen how to accept contactless cards and Apple Pay with Tap to Pay on iPhone. You can review this guide any time from Settings.',
    educationWatchAgain: 'Watch the guide again',
    tryItNow: 'Try It Now',
    // Legal disclaimers (Apple-required)
    disclaimerShort: 'Terms apply.',
    disclaimerFull: 'Tap to Pay on iPhone requires a supported payment app and the latest version of iOS. Update to the latest version by going to Settings > General > Software Update. Tap Download and Install. Some contactless cards may not be accepted. Transaction limits may apply. The Contactless Symbol is a trademark owned by and used with permission of EMVCo, LLC. Tap to Pay on iPhone is not available in all markets. When a payment is processed, Apple doesn\'t store card numbers on the device or on Apple servers.',
  },
  errors: {
    dbInit: 'Failed to initialize database',
    dbCorrupted: 'Database is corrupted',
    dbExportRemaining: 'Export Remaining Data',
    dbReset: 'Reset Database',
    orderFailed: 'Failed to create order. Please try again.',
    generic: 'Something went wrong. Please try again.',
  },
} as const;
