// Search keywords for stickers. Keyed by sticker `id` (e.g. 'food/cucumber').
//
// Each sticker's `name` and `id` are already searched directly via substring
// match in StickerPickerModal — so you only need to add aliases here when
// the common-language search term ISN'T a substring of the technical name.
//
// Examples of mismatches that require aliases:
//   food/leafy_green  ← people search "lettuce"
//   food/cucumber     ← people search "pickle"
//   drinks/cup_with_straw ← people search "soda" or "milkshake"
//
// Hand-curated, not auto-generated. Safe to edit by hand. Add menu-relevant
// aliases as merchants report search misses.

export const STICKER_KEYWORDS: Record<string, string[]> = {
  // ── FOOD ─────────────────────────────────────────────────────────────
  'food/leafy_green': ['lettuce', 'greens', 'salad greens', 'romaine', 'spinach', 'kale', 'arugula', 'mixed greens', 'mesclun'],
  'food/cucumber': ['pickle', 'pickles', 'gherkin', 'dill'],
  'food/fries': ['chips', 'french fries', 'frites', 'potato', 'shoestring'],
  'food/poultry_leg': ['chicken', 'drumstick', 'wing', 'leg quarter', 'turkey leg'],
  'food/cut_of_meat': ['steak', 'beef', 'pork chop', 'ribeye', 'sirloin', 'filet', 'brisket', 'porkchop'],
  'food/meat_on_bone': ['ribs', 'lamb chop', 't-bone', 'tomahawk', 'rack'],
  'food/egg': ['scrambled', 'omelette', 'omelet', 'sunny side', 'over easy', 'poached'],
  'food/baguette': ['french bread', 'loaf'],
  'food/bread': ['loaf', 'toast', 'sourdough', 'white bread', 'wheat', 'rye'],
  'food/croissant': ['pastry', 'breakfast pastry', 'french pastry'],
  'food/donut': ['doughnut', 'glazed', 'sprinkled', 'old fashioned'],
  'food/cookie': ['biscuit', 'snickerdoodle', 'chocolate chip'],
  'food/cake': ['layer cake', 'slice', 'slice of cake'],
  'food/birthday_cake': ['birthday', 'celebration cake'],
  'food/cupcake': ['cup cake', 'mini cake'],
  'food/custard': ['pudding', 'flan', 'creme brulee', 'creme caramel'],
  'food/honey_pot': ['honey', 'syrup', 'agave'],
  'food/ice_cream': ['gelato', 'scoop', 'sundae', 'two scoops', 'sorbet'],
  'food/soft_ice_cream': ['frozen yogurt', 'frogurt', 'fro yo', 'froyo', 'ice cream cone', 'soft serve', 'twist'],
  'food/shaved_ice': ['snow cone', 'slushie', 'slushy', 'frappe', 'frap', 'granita', 'icee'],
  'food/popcorn': ['kettle corn', 'movie snack'],
  'food/candy': ['sweets', 'sweet', 'hard candy', 'gummies', 'gummy', 'gummy bear'],
  'food/lollipop': ['sucker', 'candy on stick', 'dum dum'],
  'food/chocolate_bar': ['candy bar', 'milk chocolate', 'dark chocolate', 'kit kat', 'hershey'],
  'food/tomato': ['roma', 'cherry tomato', 'beefsteak', 'ketchup', 'heirloom'],
  'food/onion': ['red onion', 'white onion', 'yellow onion', 'shallot', 'scallion', 'green onion'],
  'food/garlic': ['clove', 'fresh garlic', 'minced garlic'],
  'food/avocado': ['guac', 'guacamole', 'hass'],
  'food/bell_pepper': ['capsicum', 'red pepper', 'green pepper', 'yellow pepper', 'sweet pepper'],
  'food/hot_pepper': ['chili', 'chilli', 'jalapeno', 'habanero', 'spicy', 'ghost pepper', 'chipotle', 'serrano', 'cayenne'],
  'food/mushroom': ['shroom', 'button', 'portobello', 'cremini', 'shitake', 'oyster', 'truffle'],
  'food/broccoli': ['brassica', 'green veggie', 'crucifer'],
  'food/carrot': ['veggie', 'root veg', 'baby carrot'],
  'food/corn': ['maize', 'cob', 'sweet corn', 'corn on the cob', 'elote'],
  'food/eggplant': ['aubergine'],
  'food/olive': ['olives', 'green olives', 'black olives', 'kalamata'],
  'food/falafel': ['chickpea', 'garbanzo', 'middle eastern'],
  'food/coconut': ['tropical'],
  'food/lemon': ['citrus', 'meyer'],
  'food/tangerine': ['orange', 'citrus', 'mandarin', 'satsuma', 'clementine'],
  'food/apple': ['fruit'],
  'food/red_apple': ['fruit', 'red delicious', 'gala', 'fuji'],
  'food/green_apple': ['granny smith', 'fruit', 'tart apple'],
  'food/banana': ['fruit', 'plantain'],
  'food/grapes': ['fruit', 'red grapes', 'green grapes', 'concord'],
  'food/strawberry': ['berry', 'fruit', 'strawberries'],
  'food/blueberries': ['berry', 'blueberry', 'fruit'],
  'food/cherries': ['cherry', 'fruit', 'sour cherry', 'maraschino', 'bing'],
  'food/peach': ['fruit', 'stone fruit', 'nectarine'],
  'food/pear': ['fruit', 'bartlett'],
  'food/kiwi': ['fruit', 'kiwifruit'],
  'food/mango': ['tropical', 'fruit'],
  'food/watermelon': ['melon', 'fruit'],
  'food/pineapple': ['tropical', 'fruit'],
  'food/pasta': ['spaghetti', 'noodle', 'noodles', 'italian', 'macaroni', 'fettuccine', 'penne', 'rigatoni', 'linguine', 'ravioli'],
  'food/curry_rice': ['curry', 'indian', 'thai', 'japanese curry', 'tikka masala'],
  'food/cooked_rice': ['rice', 'white rice', 'jasmine', 'basmati', 'brown rice'],
  'food/rice_ball': ['onigiri', 'japanese'],
  'food/sushi': ['japanese', 'nigiri', 'sashimi', 'maki', 'roll', 'temaki'],
  'food/bento_box': ['japanese', 'lunch box', 'lunch'],
  'food/dumpling': ['pierogi', 'gyoza', 'potsticker', 'wonton', 'momo', 'xiao long bao'],
  'food/fried_shrimp': ['shrimp', 'tempura', 'prawn', 'crustacean'],
  'food/fortune_cookie': ['chinese'],
  'food/burrito': ['wrap', 'mexican', 'chimichanga'],
  'food/taco': ['mexican', 'taco tuesday', 'street taco'],
  'food/tamale': ['mexican'],
  'food/stuffed_flatbread': ['pita', 'gyro', 'naan', 'falafel wrap', 'lebanese', 'middle eastern', 'wrap', 'shawarma'],
  'food/soup': ['broth', 'chowder', 'bisque'],
  'food/pot_of_food': ['stew', 'casserole', 'chili', 'slow cooker', 'dutch oven', 'pot pie'],
  'food/steaming_bowl': ['ramen', 'pho', 'noodle soup', 'hot bowl', 'udon', 'soba', 'japanese noodle'],
  'food/cooking': ['frying pan', 'skillet', 'fry', 'pan', 'cookware', 'sauté'],
  'food/salad': ['bowl', 'greens', 'garden salad', 'caesar salad', 'side salad'],
  'food/bacon': ['pork belly', 'strips', 'breakfast meat', 'rashers'],
  'food/sandwich': ['sub', 'hoagie', 'panini', 'melt', 'club', 'grilled cheese', 'blt'],
  'food/hot_dog': ['frank', 'frankfurter', 'sausage in bun', 'hotdog', 'weiner', 'chili dog'],
  'food/pretzel': ['bavarian', 'soft pretzel', 'salted'],
  'food/bagel': ['lox', 'cream cheese'],
  'food/pancakes': ['flapjack', 'hotcake', 'breakfast', 'stack', 'short stack'],
  'food/waffle': ['belgian', 'buttermilk', 'breakfast'],
  'food/burger': ['hamburger', 'cheeseburger', 'patty', 'slider', 'double'],
  'food/pizza': ['slice', 'pepperoni', 'margherita'],
  'food/pie': ['pastry', 'apple pie', 'pumpkin pie', 'pecan pie'],

  // ── DRINKS ────────────────────────────────────────────────────────────
  'drinks/coffee': ['hot coffee', 'americano', 'drip', 'mocha', 'latte', 'cappuccino', 'espresso', 'cold brew', 'brew', 'java', 'cuppa joe', 'pour over', 'macchiato'],
  'drinks/tea': ['hot tea', 'green tea', 'black tea', 'chai', 'herbal tea', 'iced tea', 'matcha'],
  'drinks/teacup': ['chai', 'herbal', 'oolong'],
  'drinks/teapot': ['kettle', 'brew', 'infusion'],
  'drinks/mate': ['yerba mate', 'herbal', 'south american', 'gourd'],
  'drinks/bubble_tea': ['boba', 'milk tea', 'tapioca', 'taiwan'],
  'drinks/cup_with_straw': ['soda', 'soft drink', 'pop', 'fountain drink', 'juice', 'smoothie', 'milkshake', 'shake', 'slushie', 'slushy', 'frappe', 'frap', 'iced coffee', 'cold drink', 'takeaway', 'to go', 'lemonade', 'iced'],
  'drinks/beverage_box': ['juice box', 'juice', 'capri sun', 'drink box', 'kids drink'],
  'drinks/bottle': ['water bottle', 'plastic bottle'],
  'drinks/water': ['h2o', 'agua', 'sparkling water', 'still water'],
  'drinks/droplet': ['water', 'drop', 'rain'],
  'drinks/milk': ['dairy', 'almond milk', 'oat milk', 'soy milk', 'whole milk', 'skim', '2 percent', 'half and half', 'creamer'],
  'drinks/baby_bottle': ['infant', 'formula', 'baby'],
  'drinks/beer': ['lager', 'ale', 'ipa', 'brew', 'pint', 'stout', 'pilsner', 'draft', 'draught', 'craft beer'],
  'drinks/clinking_beer': ['cheers', 'toast', 'pint', 'brew'],
  'drinks/clinking_glasses': ['cheers', 'toast', 'champagne', 'celebration'],
  'drinks/wine': ['red wine', 'white wine', 'glass of wine', 'rose', 'vino', 'merlot', 'cabernet', 'chardonnay', 'sauvignon'],
  'drinks/cocktail': ['martini', 'mixed drink', 'alcohol', 'manhattan', 'negroni', 'margarita'],
  'drinks/tropical_drink': ['pina colada', 'mai tai', 'daiquiri', 'tiki', 'vacation', 'beach', 'frozen drink', 'paloma'],
  'drinks/tumbler': ['whiskey', 'scotch', 'bourbon', 'rocks', 'neat', 'on the rocks', 'glass', 'rum', 'vodka', 'gin', 'liquor', 'old fashioned', 'lowball'],
  'drinks/sake': ['japanese', 'rice wine'],
  'drinks/popping_cork': ['champagne', 'celebrate', 'bubbly', 'prosecco', 'new year'],
  'drinks/pouring_liquid': ['pour', 'mix', 'mixology'],

  // ── RETAIL ────────────────────────────────────────────────────────────
  'retail/backpack': ['bag', 'pack', 'school bag', 'knapsack', 'rucksack', 'daypack'],
  'retail/bag': ['tote', 'shopping bag', 'carry'],
  'retail/book': ['novel', 'textbook', 'paperback', 'hardcover', 'reading'],
  'retail/camera': ['photography', 'photo', 'dslr'],
  'retail/camera_flash': ['photo', 'photography', 'snap'],
  'retail/candle': ['scented', 'jar candle', 'wax', 'pillar candle'],
  'retail/cart': ['shopping cart', 'trolley', 'basket', 'buggy'],
  'retail/coat': ['jacket', 'parka', 'outerwear', 'overcoat'],
  'retail/crown': ['royal', 'queen', 'king', 'tiara'],
  'retail/dress': ['clothing', 'gown', 'frock', 'sundress'],
  'retail/gem': ['diamond', 'jewel', 'jewelry', 'jewellery', 'ruby', 'emerald', 'sapphire'],
  'retail/gift': ['present', 'box', 'wrapped'],
  'retail/glasses': ['spectacles', 'eye glasses', 'eyewear', 'readers'],
  'retail/gloves': ['mittens', 'hand warmers', 'winter'],
  'retail/graduation_cap': ['mortarboard', 'graduation', 'university', 'college', 'alumni'],
  'retail/handbag': ['purse', 'clutch', 'bag'],
  'retail/hat': ['cap', 'beanie', 'fedora', 'headwear', 'baseball cap'],
  'retail/headphone': ['headphones', 'earphones', 'audio', 'music', 'earbuds'],
  'retail/high_heel': ['pumps', 'heels', 'stiletto', 'dress shoe', 'womens shoe'],
  'retail/hiking_boot': ['boot', 'work boot', 'outdoor', 'trail'],
  'retail/jeans': ['denim', 'pants', 'trousers', 'levis'],
  'retail/kimono': ['japanese robe', 'robe', 'yukata'],
  'retail/laptop': ['computer', 'macbook', 'notebook', 'pc'],
  'retail/lipstick': ['makeup', 'beauty', 'cosmetics', 'lip'],
  'retail/microphone': ['mic', 'karaoke', 'recording', 'audio'],
  'retail/mobile_phone': ['phone', 'smartphone', 'iphone', 'cell', 'mobile', 'android'],
  'retail/necktie': ['tie', 'bowtie', 'formal'],
  'retail/plant': ['houseplant', 'potted plant', 'succulent', 'greenery'],
  'retail/purse': ['handbag', 'clutch'],
  'retail/ring': ['jewelry', 'jewellery', 'wedding ring', 'engagement ring'],
  'retail/sandal': ['flip flop', 'slipper', 'summer shoe'],
  'retail/sari': ['indian', 'traditional', 'indian dress'],
  'retail/scarf': ['wrap', 'shawl', 'winter'],
  'retail/shirt': ['t shirt', 'tshirt', 'top', 'tee', 'button down', 'polo'],
  'retail/shorts': ['bermudas', 'summer pants'],
  'retail/sneaker': ['sneakers', 'athletic shoe', 'tennis shoe', 'running shoe', 'kicks', 'trainers'],
  'retail/soap': ['bar soap', 'hand soap', 'cleansing'],
  'retail/socks': ['hosiery', 'sock pair'],
  'retail/speaker': ['audio', 'sound', 'bluetooth speaker'],
  'retail/star': ['favorite', 'favourite', 'rating'],
  'retail/sunglasses': ['shades', 'sun glasses', 'sunnies'],
  'retail/swimsuit': ['bikini', 'swim', 'beachwear', 'bathing suit'],
  'retail/top_hat': ['formal hat', 'magician', 'tuxedo'],
  'retail/watch': ['timepiece', 'wristwatch', 'smartwatch'],

  // ── SERVICE ───────────────────────────────────────────────────────────
  'service/bandage': ['band aid', 'plaster', 'first aid', 'medical'],
  'service/banknote': ['cash', 'bill', 'dollar', 'money', 'paper money'],
  'service/bell': ['notification', 'alert', 'ring', 'service bell'],
  'service/bone': ['dog bone', 'treat', 'pet'],
  'service/briefcase': ['business', 'office', 'work bag'],
  'service/calendar': ['schedule', 'date', 'appointment', 'booking'],
  'service/cat': ['kitty', 'feline', 'pet'],
  'service/clock': ['time', 'watch', 'hours'],
  'service/credit_card': ['card', 'debit', 'payment', 'plastic', 'visa', 'mastercard'],
  'service/dog': ['puppy', 'pet', 'canine', 'woof'],
  'service/fire': ['flame', 'hot', 'burning'],
  'service/glowing_star': ['shooting star', 'premium', 'special', 'magic'],
  'service/hammer': ['tool', 'construction', 'handyman', 'carpentry'],
  'service/hammer_wrench': ['tools', 'repair', 'mechanic', 'maintenance', 'handyman'],
  'service/heart': ['love', 'favorite', 'favourite', 'like'],
  'service/key': ['lock', 'locksmith', 'access'],
  'service/lightbulb': ['idea', 'electrician', 'light', 'bulb', 'electricity'],
  'service/lotion': ['cream', 'moisturizer', 'skincare'],
  'service/magnifier': ['search', 'magnifying glass', 'zoom', 'inspection', 'detective'],
  'service/memo': ['note', 'paper', 'memo pad', 'pad'],
  'service/money_bag': ['cash', 'money', 'dollars', 'sack'],
  'service/nut_bolt': ['hardware', 'fastener', 'mechanic'],
  'service/palette': ['paint', 'art', 'painter', 'artist'],
  'service/paw': ['pet', 'animal', 'paw print', 'dog cat'],
  'service/pencil': ['write', 'writing', 'drawing', 'draw'],
  'service/pill': ['medicine', 'medication', 'prescription', 'capsule', 'tablet', 'drug', 'rx'],
  'service/razor': ['shave', 'shaving', 'barber', 'blade'],
  'service/receipt': ['invoice', 'bill', 'paper receipt'],
  'service/scissors': ['cut', 'shears', 'barber', 'hairdresser', 'salon', 'haircut'],
  'service/screwdriver': ['tool', 'repair', 'phillips', 'flathead'],
  'service/seedling': ['plant', 'gardening', 'sprout', 'growing', 'baby plant'],
  'service/service_dog': ['assistance dog', 'guide dog'],
  'service/snowflake': ['snow', 'winter', 'ice', 'cold', 'frozen'],
  'service/sparkles': ['shiny', 'clean', 'magic', 'fresh', 'new'],
  'service/speech_balloon': ['chat', 'message', 'talk', 'comment', 'speech', 'conversation'],
  'service/stethoscope': ['doctor', 'medical', 'physician', 'nurse'],
  'service/syringe': ['needle', 'injection', 'vaccine', 'vaccination', 'shot', 'medical'],
  'service/ticket': ['pass', 'admission', 'entry', 'voucher'],
  'service/toolbox': ['tools', 'repair', 'handyman', 'mechanic'],
  'service/tooth': ['dental', 'dentist', 'teeth'],
  'service/toothbrush': ['dental', 'brush', 'hygiene'],
  'service/wave': ['hello', 'hi', 'greeting', 'hand'],
  'service/wrench': ['tool', 'plumbing', 'mechanic', 'spanner'],
};
